Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Documentation:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.6.2

  Exclude:
    - 'Gemfile'
    - 'Rakefile'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/{rails,rake,setup,bundle}'
    - 'db/**'
